### ISSUE TITLE
Client side bundling doesn't eliminate dead code in production

### ISSUE THREAD

**Issue by benjamn** [meteor/meteor-feature-requests#94]
Migrated from: meteor/meteor#6402

**Comment by ninjaPixel** [comment]
> We are using Material-UI 
@skirunman FYI I'm also seeing this with an empty, vanilla React app too.

**Comment by sunlee-newyork** [comment]
+1, using Material-UI as well with Meteor 1.5.2.1

**Comment by skirunman** [comment]
Issue with not showing "production" version of React Developer Tools icon was resolved for us when we upgraded to Meteor 1.6-beta.30. Guessing maybe an updated version of Babel solved this for us? Meteor 1.6 is now a [release candidate](https://github.com/meteor/meteor/tree/release/METEOR%401.6-rc.0) so maybe give it a try if you can.

**Comment by santiagopuentep** [comment]
For us the "production" version of React issue was solved by Meteor 1.5.2.

**Comment by ninjaPixel** [comment]
I'm still getting this issue. Have tried the latest `METEOR@1.6-rc.2`. BTW I'm using React v 16

**Comment by aliogaili** [comment]
I'm getting this issue as well, the bundle visualizer is reporting that the react dom size is 294kb and I can see it has react-dom-development.js (which is 183kb).

Therefore I'm not getting an accurate report on the bundle size.

**Comment by SaniMusic** [comment]
@aliogaili Worked for me also on 1.6 rc6 ..

**Comment by vuhrmeister** [comment]
I'm also getting this error message with Meteor 1.6 and React 16.1.1. The react-dom size is only 91kb though and the visualizer shows that it uses `react-dom.production.min.js`.

**Comment by KoenLav** [comment]
@benjamn this can be closed?
